"""
Django settings for trips project.

Generated by 'django-admin startproject' using Django 1.8.4.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os
import dj_database_url

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'gmtng+-cpb^e&fc#x_6bpgtp!awt#929sd583mqd7przjn!!0+'

ON_HEROKU = True if 'DATABASE_URL' in os.environ else False

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False if ON_HEROKU else True

ALLOWED_HOSTS = ['localhost', '127.0.0.1', 'travelspots.herokuapp.com',
                 'imtripping.com']


CRISPY_TEMPLATE_PACK = 'bootstrap3'


# Application definition

INSTALLED_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'recommend',

    'crispy_forms',
)

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
)

ROOT_URLCONF = 'trips.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'trips.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

LOCAL_DB = 'postgres://david:test@localhost:5432/trips'
# Use this line if connecting to a local database. Use the if ON_HEROKU
# statement below if connecting to heroku's database from a local machine.
DATABASES = {'default': dj_database_url.config(default=LOCAL_DB)}

# For connecting to Heroku's database from a local machine.
# This if/else prevents loading the .gitignored private file if on Heroku.
if ON_HEROKU:
    DATABASES = {'default': dj_database_url.config()}
else:
    from recommend.private import heroku_db_url
    DATABASES = {'default': dj_database_url.config(default=heroku_db_url)}


# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

STATIC_URL = '/static/'
